Тема “Вычисления с помощью Numpy”

Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7],])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
a.mean(axis=0)

array([2. , 8.4])

In [5]:
mean_a = a.mean(axis=0)

In [6]:
mean_a

array([2. , 8.4])

Задание 2

In [7]:
a_centered = a - mean_a

In [8]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [9]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [10]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

Задание 4

In [11]:
m = np.cov(a.T)[0, 1]

In [12]:
m

2.0

Тема “Работа с данными в Pandas”

Задание 1

In [14]:
import pandas as pd

In [15]:
D = {
    "autor_id": [1, 2, 3],
    "autor_name": ['Тургенев', 'Чехов', 'Островский']
}

In [16]:
autor = pd.DataFrame(D)

In [17]:
autor

autor_id  autor_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [18]:
bb = {
    "autor_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

In [20]:
book = pd.DataFrame(bb)

In [21]:
book

autor_id            book_title  price
0         1           Отцы и дети    450
1         1                 Рудин    300
2         1     Дворянское гнездо    350
3         2      Толстый и тонкий    500
4         2       Дама с собачкой    450
5         3                 Гроза    370
6         3  Таланты и поклонники    290

Задание 2

In [22]:
pd.merge(autor, book, on='autor_id', how='inner')

autor_id  autor_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

In [23]:
pd.merge(autor, book, on='autor_id', how='outer')

autor_id  autor_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

In [24]:
autor_price = pd.merge(autor, book, on='autor_id', how='inner')

In [25]:
autor_price

autor_id  autor_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

Задание 3

In [26]:
top5 = autor_price.nlargest(5, "price")

In [27]:
top5

autor_id  autor_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островский              Гроза    370
2         1    Тургенев  Дворянское гнездо    350

Задание 4

In [29]:
autor_name = autor_price['autor_name'].unique()

In [30]:
autor_name

array(['Тургенев', 'Чехов', 'Островский'], dtype=object)

In [32]:
groupby = autor_price.groupby('autor_name')

In [33]:
groupby['price'].mean()

autor_name
Островский    330.000000
Тургенев      366.666667
Чехов         475.000000
Name: price, dtype: float64

In [34]:
groupby['price'].min()

autor_name
Островский    290
Тургенев      300
Чехов         450
Name: price, dtype: int64

In [35]:
groupby['price'].max()

autor_name
Островский    370
Тургенев      450
Чехов         500
Name: price, dtype: int64

In [47]:
autor_stat = autor_price.groupby('autor_name').agg({'price':['min', 'max', 'mean']})

In [49]:
autor_stat = autor_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

In [50]:
autor_stat

price                      
           min_price max_price  mean_price
autor_name                                
Островский       290       370  330.000000
Тургенев         300       450  366.666667
Чехов            450       500  475.000000

Задание 5

In [52]:
autor_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [53]:
autor_price

autor_id  autor_name            book_title  price    cover
0         1    Тургенев           Отцы и дети    450  твердая
1         1    Тургенев                 Рудин    300   мягкая
2         1    Тургенев     Дворянское гнездо    350   мягкая
3         2       Чехов      Толстый и тонкий    500  твердая
4         2       Чехов       Дама с собачкой    450  твердая
5         3  Островский                 Гроза    370   мягкая
6         3  Островский  Таланты и поклонники    290   мягкая

In [54]:
?pd

In [56]:
book_info = pd.pivot_table(autor_price, values = 'price', index = ['autor_name'], columns = ['cover'], aggfunc = np.sum)

In [57]:
book_info['мягкая'] = book_info['мягкая'].fillna(0)

In [58]:
book_info['твердая'] = book_info['твердая'].fillna(0)

In [59]:
book_info

cover       мягкая  твердая
autor_name                 
Островский   660.0      0.0
Тургенев     650.0    450.0
Чехов          0.0    950.0

In [60]:
book_info.to_pickle('book_info.pkl')

In [61]:
book_info2 = pd.read_pickle('book_info.pkl')

In [62]:
book_info.equals(book_info2)

True